FROM python:3.7-buster

LABEL maintainer="mahdi.benjelloul@ipp.eu"

RUN apt-get update && \
  apt-get install -y r-base && \
  R -e 'install.packages(c("configr", "proxy", "StatMatch"), repos = "http://cran.us.r-project.org")'
